### ISSUE TITLE
Build fails due to duplicate resource error

### ISSUE THREAD

**Issue by btat** [rancher/rancher-product-docs#124]
When attempting to build the docs I'm currently getting the error below.

```
npx antora --stacktrace --log-format=pretty --log-level=info \
        playbook-local.yml \
        2>&1 | tee tmp/local-build.log 2>&1
[16:32:06.162] FATAL (antora): Duplicate attachment: latest@shared::attachment$rancher-psact.yaml
    1: /home/btat/rancher-product-docs/shared/modules/ROOT/attachments/rancher-psact.yaml in /home/btat/rancher-product-docs (branch: main <worktree> | start path: shared)
    2: shared/modules/ROOT/attachments/rancher-psact.yaml in /home/btat/rancher-product-docs/.git (branch: v2.10.1 <remotes/origin> | start path: shared)
    Cause: Error
        at ContentCatalog.addFile (/home/btat/rancher-product-docs/node_modules/@antora/content-classifier/lib/content-catalog.js:153:17)
        at /home/btat/rancher-product-docs/node_modules/@antora/content-classifier/lib/classify-content.js:41:87
        at Array.forEach (<anonymous>)
        at /home/btat/rancher-product-docs/node_modules/@antora/content-classifier/lib/classify-content.js:41:13
        at Map.forEach (<anonymous>)
        at GeneratorContext.classifyContent (/home/btat/rancher-product-docs/node_modules/@antora/content-classifier/lib/classify-content.js:36:6)
        at /home/btat/rancher-product-docs/node_modules/@antora/site-generator/lib/generate-site.js:26:38
```

The duplicate resource that it logs varies between runs. In our case it's either an attachment or partial since those are what we have in the /shared component, but it could be any of pages, partials, images, attachments, or examples. E.g.

```
[16:33:39.344] FATAL (antora): Duplicate partial: latest@shared::partial$en/cni-popularity.adoc
```

**Comment by btat** [comment]
After investigating this seems related to our local playbook file not specifying a branch under the content source. As per the [Antora docs](https://docs.antora.org/antora/latest/playbook/content-branches/#default), when the branches key is not specified 

> Antora will inherit the default branches filter, [HEAD, v{0..9}*]. That means Antora will use files from the current (for local) or default (for remote) branch (e.g., main) as well as any branch that begins with the letter v followed immediately by a number (e.g., v2.0.x). You can override this inherited value per content source by setting the branches key.

This has only become an issue recently since we created release branches for the December release cycle and these branches match the filter pattern. E.g. `v2.8.11, v2.9.5, v2.10.1`.

Initially we specified `main` in the branches field in this repo (and is still the case for other repos in our portfolio), but changes on feature branches could not be tested properly when set to `main`.
